# Generated by Django 5.0.2 on 2024-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_price', models.IntegerField()),
            ],
            options={
                'db_table': 'stock_prices',
            },
        ),
    ]
